<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
	<AssemblyName>nutho313.QSBT1_Streamdeck</AssemblyName>
    <RootNamespace>QSBT1_Streamdeck</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StreamDeck-Tools" Version="6.4.0" />
    <PackageReference Include="Newtonsoft.Json"  Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="manifest.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="images\**\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="pi\**\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
